var b=!1,e=null,f=0,h=0,k={x:0,y:0},m={h:{angle:0,a:0},i:0,f:{b:0,c:0},g:{b:0,c:0}},n,p,q,r=[{x:0,y:0}],t=0,u=!0,v={x:0,y:0},w=!1,x=!0,y="eng";function z(a){switch(a.code){case a.PERMISSION_DENIED:alert("User did not share geolocation data");break;case a.POSITION_UNAVAILABLE:alert("Could not detect current position");break;case a.TIMEOUT:alert("Retrieving position timedout");break;default:alert("Unknown error")}}
function A(a){var c=a.coords.latitude,d=a.coords.longitude;f=c;h=d;a={x:0,y:0};c=B(c,d);angleDelta=m.h.angle-c.angle;angle=m.h.angle-angleDelta;dist=c.a*m.i;a.x=Math.cos(angle)*dist;a.y=Math.sin(angle)*dist;k=a;document.getElementById("current_location").value=f+", "+h;u=k.x>p.width||0>k.x||k.y>p.height||0>k.y?!1:!0;dist=C(k.x,k.y,r[r.length-1].x,r[r.length-1].y);dist>n&&r.push({x:k.x,y:k.y});1E3<r.length&&r.shift()}function D(a){q.beginPath();q.arc(a.x,a.y,3,0,2*Math.PI);q.stroke()}
function E(){q.clearRect(0,0,p.width,p.height);q.beginPath();q.closePath();q.drawImage(map_image,0,0,map_image.width,map_image.height,0,0,p.width,p.height);0!=x&&(q.lineWidth=1,q.strokeStyle="red",r.forEach(D));var a=k.x,c=k.y;if(0!=a||0!=c){var d=30;0==t%2&&(d-=d/4);var g=2*d/3,l=d/3;q.beginPath();q.lineWidth=5;q.strokeStyle="red";q.arc(a,c,d-l,0,2*Math.PI);q.moveTo(a-d,c);q.lineTo(a-d+g,c);q.moveTo(a+d,c);q.lineTo(a+d-g,c);q.moveTo(a,c-d,a);q.lineTo(a,c-d+g);q.moveTo(a,c+d);q.lineTo(a,c+d-g);q.stroke();
q.beginPath();q.lineWidth=2;q.strokeStyle="white";q.arc(a,c,d-l,0,2*Math.PI);q.moveTo(a-d,c);q.lineTo(a-d+g,c);q.moveTo(a+d,c);q.lineTo(a+d-g,c);q.moveTo(a,c-d,a);q.lineTo(a,c-d+g);q.moveTo(a,c+d);q.lineTo(a,c+d-g);q.stroke()}1!=u&&(q.strokeStyle=0==t%4?"white":"red",q.font="30px Arial",q.strokeText("You are not located on this map...",20,60));0==v.x&&0==v.y||0==u||0==w||(q.beginPath(),q.lineWidth=2,q.strokeStyle="black",q.moveTo(k.x,k.y),q.lineTo(v.x,v.y),q.stroke(),q.beginPath(),q.arc(v.x,v.y,7,
0,2*Math.PI),q.fill(),q.font="20px Arial",a=C(v.x,v.y,k.x,k.y),a=0==m.i?0:a/m.i,a=a.toFixed(3),q.strokeText(a+" Km",v.x,v.y-30),q.stroke())}function F(){t+=1;1E5<t&&(t=0);E()}function C(a,c,d,g){a=d-a;c=g-c;return Math.sqrt(a*a+c*c)}function B(a,c){var d=m.f.b,g=m.f.c,l={angle:0,a:0};l.a=G(d,g,a,c);var K=l.a;d=G(d,g,a,g);l.angle=Math.asin(d/K);JSON.stringify(l);return l}
function G(a,c,d,g){var l=Math.PI/180*(d-a);c=Math.PI/180*(g-c);a=Math.sin(l/2)*Math.sin(l/2)+Math.cos(Math.PI/180*a)*Math.cos(Math.PI/180*d)*Math.sin(c/2)*Math.sin(c/2);return 12742*Math.atan2(Math.sqrt(a),Math.sqrt(1-a))}function H(){document.getElementById("mySidenav").style.width="0";document.body.style.backgroundColor="white"}var I=window;b=b=!0;document.getElementById("current_location").value="Loading...";var J=document.getElementById("map_data").value.split(";",7);mapTitle=J[1];y=J[2];
m.f.b=J[3];m.f.c=J[4];m.g.b=J[5];m.g.c=J[6];document.getElementById("map_title").innerHTML=mapTitle;p=document.getElementById("map_canvas");q=p.getContext("2d");map_image=new Image;map_image.src="img.jpg";
map_image.onload=function(){var a=map_image.width/map_image.height;p.width=window.innerWidth;p.height=p.width/a;q.drawImage(map_image,0,0,map_image.width,map_image.height,0,0,p.width,p.height);m.h=B(m.g.b,m.g.c);a=C(0,0,p.width,p.height);m.i=a/m.h.a;JSON.stringify(m);n=a/250;null==e&&(e=navigator.geolocation.watchPosition(A,z,{timeout:1E4,enableHighAccuracy:!0,maximumAge:Infinity}));setInterval(F,500)};
p.addEventListener("mousedown",function(a){var c=p.getBoundingClientRect();v={x:a.clientX-c.left,y:a.clientY-c.top};E()},!1);p.addEventListener("touchstart",function(a){var c=p.getBoundingClientRect();v={x:a.touches[0].clientX-c.left,y:a.touches[0].clientY-c.top};E()},!1);document.getElementById("menuOpen").onclick=function(){0!=b&&(document.getElementById("mySidenav").style.width="270px",document.body.style.backgroundColor="rgba(0,0,0,0.4)")};document.getElementById("myCloseBtn").onclick=H;
var L="Show/Hide distance ruler";"heb"==y&&(L="\u05d4\u05e6\u05d2/\u05d4\u05e1\u05ea\u05e8 \u05e1\u05e8\u05d2\u05dc \u05de\u05e8\u05d7\u05e7");document.getElementById("menuItem1").innerHTML=L;document.getElementById("menuItem1").onclick=function(){w=0==w?!0:!1;H()};L="Keep screen on";"heb"==y&&(L="\u05e9\u05de\u05d5\u05e8 \u05d0\u05ea \u05d4\u05de\u05e1\u05da \u05d3\u05dc\u05d5\u05e7");document.getElementById("menuItem2").innerHTML=L;document.getElementById("menuItem2").onclick=function(){H()};
L="Show/Hide tail of locations";"heb"==y&&(L="\u05d4\u05e6\u05d2/\u05d4\u05e1\u05ea\u05e8 \u05de\u05d9\u05e7\u05d5\u05de\u05d9\u05dd \u05e7\u05d5\u05d3\u05de\u05d9\u05dd");document.getElementById("menuItem3").innerHTML=L;document.getElementById("menuItem3").onclick=function(){x=0==x?!0:!1;H()};L="Save for Offline use";"heb"==y&&(L="\u05e9\u05de\u05d5\u05e8 \u05d0\u05ea \u05d4\u05d3\u05e3 \u05dc\u05e9\u05d9\u05de\u05d5\u05e9 \u05dc\u05dc\u05d0 \u05d0\u05d9\u05e0\u05d8\u05e8\u05e0\u05d8");
document.getElementById("menuItem4").innerHTML=L;document.getElementById("menuItem4").onclick=function(){H()};I.onload=void 0;